name: CI/CD Pipeline Java com H2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build & Test com Java
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build e Testes com Maven
        run: mvn -B verify
        working-directory: ./gerenciadortarefas # <<< ESSA É A LINHA QUE CORRIGE O PROBLEMA