name: CI/CD Pipeline Java com H2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build & Test com Java
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4
      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build e Testes com Maven
        run: mvn -B verify
        working-directory: ./gerenciadortarefas

  build-and-push-docker:
    name: Construir e Publicar Imagem Docker
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Construir e enviar a imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: ./gerenciadortarefas
          push: true
          tags: ghcr.io/scarletykaro10/${{ github.event.repository.name }}:latest

  deploy-staging:
    name: Deploy em Homologação (Staging)
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    environment:
      name: staging
      url: https://staging.gerenciador-tarefas.com
    steps:
      - name: Deploy para Staging
        run: |
          echo "Iniciando deploy para o ambiente de Staging..."
          echo "URL do ambiente: ${{ steps.deployment.outputs.page_url }}"
          echo "Deploy em Staging concluído!"

  deploy-production:
    name: Deploy em Produção
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production
      url: https://gerenciador-tarefas.com
    steps:
      - name: Deploy para Produção
        run: |
          echo "Iniciando deploy para o ambiente de Produção..."
          echo "URL do ambiente: ${{ steps.deployment.outputs.page_url }}"
          echo "Deploy em Produção concluído!"